{% set name = "apache-airflow-providers-fab" %}
{% set version = "3.0.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_fab-{{ version }}.tar.gz
  sha256: c17a8cb80c32c498a5feaa004d0bd3e8614ef6358abaa664b06e3a745e4507ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - flask-sqlalchemy >=3.0.5
    - flask_limiter >3,<4,!=3.13
    - msgpack-python >=1.0.0
    - sqlalchemy >=1.4.36,<2
    - python >={{ python_min }},<3.13
    - apache-airflow >=3.0.2
    - apache-airflow-providers-common-compat >=1.8.0
    - blinker >=1.6.2
    - flask >=2.2.1,<2.3
    - flask-appbuilder ==5.0.1
    - flask-login >=0.6.2
    - flask-session >=0.8.0
    - flask-wtf >=1.1.0
    - connexion >=2.14.2,<3.0
    - jmespath >=0.7.0
    - werkzeug >=2.2,<4
    - wtforms >=3.0,<4
    - flask-limiter >3,<4,!=3.13

test:
  imports:
    - airflow.providers.fab
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-fab for Apache Airflow
  license: Apache-2.0 AND MIT
  license_file:
    - src/airflow/providers/3rd-party-licenses/LICENSES-ui.txt
    - src/airflow/providers/fab/LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
