{% set name = "apache-airflow-providers-fab" %}
{% set version = "1.5.1" %}
{% set python_min = python_min|default("3.9") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_fab-{{ version }}.tar.gz
  sha256: b0f253612254c458817b662211cbfa5204159ec938b0a925954328c9831e291e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - flit-core ==3.10.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.9.0
    - apache-airflow-providers-common-compat >=1.2.1
    - flask-appbuilder ==4.5.2
    - flask-login >=0.6.2
    - flask >=2.2,<2.3
    - google-re2 >=1.0
    - jmespath >=0.7.0

test:
  imports:
    - airflow.providers.fab
  commands:
    - pip check
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-fab for Apache Airflow
  license: Apache-2.0
  license_family: Apache
  license_file: airflow/providers/fab/LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
