{% set name = "apache-airflow-providers-fab" %}
{% set version = "1.5.4" %}
{% set python_min = python_min|default("3.9") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_fab-{{ version }}.tar.gz
  sha256: 3884d1f57f61e9fe13b47e699b58edbe7fe79cc0c10b228516f27271aa1237e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.10.1
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.11.1
    - apache-airflow-providers-common-compat >=1.2.1
    - flask-appbuilder ==4.5.4
    - flask-login >=0.6.3
    - flask >=2.2,<3
    - google-re2 >=1.0
    - jmespath >=0.7.0

test:
  imports:
    - airflow.providers.fab
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-fab for Apache Airflow
  license: Apache-2.0
  license_family: Apache
  license_file: airflow/providers/fab/LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
