{% set name = "apache-airflow-providers-fab" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_fab-{{ version }}.tar.gz
  sha256: 9b02774cfdf13fa27266c80bf4436ee773081f62ba1b765d2b44a4b239442e5d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }},<3.13
    - apache-airflow >=3.0.2
    - apache-airflow-providers-common-compat >=1.8.0
    # more restrictive for python <3.13
    - blinker >=1.6.2
    # more restrictive for python <3.13
    - flask >=2.2.1
    - flask-appbuilder ==5.0.1
    # more restrictive for python <3.13
    - flask-login >=0.6.2
    # more restrictive for python <3.13
    - flask-session >=0.8.0
    # more restrictive for python <3.13
    - msgpack >=1.0.0
    # more restrictive for python <3.13
    - flask-sqlalchemy >=3.0.5
    # more restrictive for python <3.13
    - sqlalchemy >=1.4.36
    # more restrictive for python <3.13
    - flask-wtf >=1.1.0
    # more restrictive for python <3.13
    - connexion >=2.14.2
    # more restrictive for python <3.13
    - jmespath >=0.7.0
    # more restrictive for python <3.13
    - werkzeug >=2.2
    # more restrictive for python <3.13
    - wtforms >=3.0
    - flask_limiter >3,<4,!=3.13

test:
  imports:
    - airflow.providers.fab
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-fab for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
