{% set name = "apache-airflow-providers-fab" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_fab-{{ version }}.tar.gz
  sha256: f146e401a40cfbdf95567d249c9d39bda35ad77cdf61db28eb84c2f874f668d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    # skip for now to avoid circular dependency
    # - apache-airflow >=2.9.0
    - flask-appbuilder ==4.4.1
    - flask-login >=0.6.2
    - flask >=2.2,<2.3
    - google-re2 >=1.0

test:
  imports:
    # skip for now because we aren't installing apache-airflow
    # - airflow.providers.fab
  commands:
    # skip for now because we aren't installing apache-airflow
    # - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-fab for Apache Airflow
  license: Apache-2.0
  license_family: Apache
  license_file: airflow/providers/fab/LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
