{% set name = "apache-airflow-providers-fab" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_fab-{{ version }}.tar.gz
  sha256: 79e9e84e0e91e557191f37f92e1c2f8784f511b3cc5c02cc985433b1a747b897

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.9.0
    - flask-appbuilder ==4.5.0
    - flask-login >=0.6.2
    - flask >=2.2,<2.3
    - google-re2 >=1.0
    - jmespath >=0.7.0

test:
  imports:
    - airflow.providers.fab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-fab for Apache Airflow
  license: Apache-2.0
  license_family: Apache
  license_file: airflow/providers/fab/LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
