context:
  name: apache-airflow-providers-fab
  version: 3.6.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_fab-${{ version }}.tar.gz
  sha256: 3e06969666bce279e3b28e5a48dc2004d7acc64ce769a58303ff5941a324c9f0

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - gitpython ==3.1.45
    - gitdb ==4.0.12
    - hatchling ==1.27.0
    - packaging ==25.0
    - pathspec ==0.12.1
    - pluggy ==1.6.0
    - smmap ==5.0.2
    - tomli ==2.2.1
    - trove-classifiers ==2025.9.11.17
  run:
    - python >=${{ python_min }}
    - apache-airflow >=3.0.2
    - apache-airflow-providers-common-compat >=1.12.0
    - blinker >=1.6.2
    - flask >=2.2.1
    - flask-appbuilder ==5.2.0
    - flask-login >=0.6.2
    - flask-session >=0.8.0
    - msgpack-python >=1.0.0
    - flask-sqlalchemy >=3.0.5
    - flask-wtf >=1.1.0
    - jmespath >=0.7.0
    - werkzeug >=2.2
    - wtforms >=3.0
    - cachetools >=6.0
    - flask-limiter >3,!=3.13
    - marshmallow >=3
tests:
  - python:
      imports:
        - airflow.providers.fab
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-fab for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
