context:
  name: apache-airflow-providers-fab
  version: "3.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_fab-${{ version }}.tar.gz
  sha256: 4bfa706c50108e59e810af5defac5b48e3c6dc22f8555360247fcacf36f7518a

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling ==1.29.0
    - packaging ==26.0
    - pathspec ==1.0.4
    - pluggy ==1.6.0
    # for all python to stay noarch: python
    - tomli ==2.4.0
    - trove-classifiers ==2026.1.14.14
  run:
    - python >=${{ python_min }}
    - apache-airflow >=3.0.2
    - apache-airflow-providers-common-compat >=1.12.0
    - blinker >=1.6.2
    - flask >=2.2.1,<2.3
    - flask-appbuilder ==5.2.0
    - flask-login >=0.6.2
    - flask-session >=0.8.0
    - msgpack-python >=1.0.0
    - flask-sqlalchemy >=3.0.5
    - flask-wtf >=1.1.0
    - jmespath >=0.7.0
    - werkzeug >=2.2,<4
    - wtforms >=3.0,<4
    - cachetools >=6.0
    - flask-limiter >3,<4,!=3.13

tests:
  - python:
      imports:
        - airflow.providers.fab
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-fab for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
