context:
  name: apache-airflow-providers-fab
  version: 3.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_fab-${{ version }}.tar.gz
  sha256: 1dd868e74b0848e74ac6962d9d0d89ef988762a61a5c1105b8687bbfadff89dd

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==3.12.0
  run:
    - python >=${{ python_min }}
    - apache-airflow >=3.0.2
    - apache-airflow-providers-common-compat >=1.12.0
    # more restrictive for python <3.13
    - blinker >=1.6.2
    # more restrictive for python <3.13
    - flask >=2.2.1,<2.3
    - flask-appbuilder ==5.0.1
    # more restrictive for python <3.13
    - flask-login >=0.6.2
    # more restrictive for python <3.13
    - flask-session >=0.8.0
    # more restrictive for python <3.13
    - msgpack-python >=1.0.0
    # more restrictive for python <3.13
    - flask-sqlalchemy >=3.0.5
    # more restrictive for python <3.13
    - flask-wtf >=1.1.0
    # more restrictive for python <3.13
    - connexion >=2.14.2,<3.0
    # more restrictive for python <3.13
    - jmespath >=0.7.0
    # more restrictive for python <3.13
    - werkzeug >=2.2,<4
    # more restrictive for python <3.13
    - wtforms >=3.0,<4
    # more restrictive for python <3.13
    - cachetools >=6.0
    - flask-limiter >3,<4,!=3.13
tests:
  - python:
      imports:
        - airflow.providers.fab
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-fab for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
